# Generated by Django 2.2.5 on 2019-11-16 02:22

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('route', models.CharField(max_length=30)),
                ('capacity', models.IntegerField()),
                ('status', models.CharField(choices=[('In service', 'In service'), ('Maintenance', 'Maintenance')], default='In service', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='map',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(default='Denton, Tx', max_length=50)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_id', models.CharField(default=None, max_length=30)),
                ('name', models.CharField(default=None, max_length=30)),
                ('color', models.CharField(default=None, max_length=30)),
                ('stps', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), size=None), size=None)),
            ],
        ),
        migrations.CreateModel(
            name='stop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_name', models.CharField(default=None, max_length=50)),
                ('latitude', models.FloatField(default=33.211073)),
                ('longitude', models.FloatField(default=-97.146241)),
            ],
        ),
    ]
