# Generated by Django 2.2.5 on 2019-10-06 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapviewer', '0004_map'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='status',
            field=models.CharField(choices=[('In service', 'In service'), ('Maintenance', 'Maintenance')], default='In service', max_length=30),
        ),
    ]
