# Generated by Django 2.2.5 on 2019-10-15 19:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mapviewer', '0005_auto_20191006_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='routes',
            name='favorited',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
