# Generated by Django 2.2.5 on 2019-10-28 17:37

from django.conf import settings
from django.db import migrations, models
import django_google_maps.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mapviewer', '0006_routes_favorited'),
    ]

    operations = [
        migrations.CreateModel(
            name='stop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_id', models.IntegerField()),
                ('stop_name', models.CharField(max_length=50)),
                ('address', django_google_maps.fields.AddressField(max_length=2000)),
                ('location', django_google_maps.fields.GeoLocationField(max_length=100)),
            ],
        ),
        migrations.RenameModel(
            old_name='Routes',
            new_name='Route',
        ),
    ]
