# Generated by Django 2.2.5 on 2019-11-03 18:08

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mapviewer', '0007_auto_20191028_1737'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Route',
            new_name='Routes',
        ),
        migrations.DeleteModel(
            name='stop',
        ),
    ]
